server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
#  cloud:
#    gateway:
#      routes:
#        - id: first-test-service
#          uri: lb://first-test-service
#          predicates:
#            - Path=/first-test-service/**
#        - id: auction-user
#          uri: lb://auction-user
#          predicates:
#            - Path=/auction-user/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/auction-user/(?<segment>.*), /$\{segment}